version: '3.8'

services:
  note-app-db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notes_db
    networks:
      - internal

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@note-app-db/notes_db
    networks:
      - internal
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.note-app-backend.rule=Host(`note-app.wordlyte.com`)"
      - "traefik.http.routers.note-app-backend.entrypoints=websecure"
      - "traefik.http.routers.note-app-backend.tls.certresolver=myresolver"
      - "traefik.http.services.note-app-backend.loadbalancer.server.port=8000"
    depends_on:
      - note-app-db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - internal
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.note-app-frontend.rule=Host(`note-app-web.wordlyte.com`)"
      - "traefik.http.routers.note-app-frontend.entrypoints=websecure"
      - "traefik.http.routers.note-app-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.note-app-frontend.loadbalancer.server.port=5173"
    depends_on:
      - backend

networks:
  internal:
  edge:
    external: true

volumes:
  postgres_data: